name: instructions_app
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:  
  http: ^0.12.0 
  flutter:
    sdk: flutter

#http: ^0.12.0 // latest one might change
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #sqflite: any
  path_provider: any
#  intl: ^0.15.7
  shared_preferences: any
  #connectivity: any
  toast: any
  flutter_spinkit: ^4.1.2+1
  dio: any
  # firebase_auth: ^0.15.3
  # cloud_firestore: ^0.13.0+1
  # firebase_storage: ^3.1.1
  #  flutter_spinkit: ^4.1.2+1
  # firebase_auth: ^0.15.3
  # cloud_firestore: ^0.13.0+1
  # firebase_storage: ^3.1.1
  # firebase_core: any
  provider: ^4.0.5+1
  # firebase_auth: 
  # firebase_core:   
  # cloud_firestore: ^0.14.0+1
  # firebase_messaging: ^7.0.3
  # **********
  firebase_core: any
  firebase_auth: ^0.16.0  
  cloud_firestore: ^0.13.6
  firebase_messaging: ^6.0.13
  # ***********
  audio_recorder: ^1.0.2
  font_awesome_flutter: ^8.8.1
  # flutter_facebook_login: ^3.0.0
  # google_sign_in: ^4.5.3
  #flutter_sound: ^4.0.4+1
  audioplayers: ^0.15.1
#  audioplayers: ^0.17.4
  flutter_sound: ^7.8.4
  record_mp3: ^2.1.0
  aes_crypt: ^0.1.1
  permission_handler:
  path:
  assets_audio_player:
  intl:
  avatar_glow:
  # button3d: ^0.1.1
  #permission_handler: ^5.0.1+1
  json_serializable: ^2.0.0
  alice: ^0.0.13
  share: ^0.6.5
  flutter_local_notifications: ^1.4.0
  # workmanager: ^0.2.3
  local_auth: ^0.6.3+4
  # android_alarm_manager_plus: ^0.6.0
  # android_alarm_manager: ^0.4.5+14
  # workmanager: ^0.4.0
  #background_fetch: ^0.7.2
  #workmanager:
# dev_dependencies:
#   flutter_test:
#     sdk: flutter
dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # plugin:
  #   androidPackage: com.jordanalcaraz.audiorecorder.audiorecorder
  #   pluginClass: AudioRecorderPlugin
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    # - assets/home2.jpg          
    # - assets/tick.png      
    # - assets/login.jpg
    # - assets/home.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
